language: ruby
notifications:
  email: false
rvm:
  - 1.9.3 # Same as Ariadne host env
install: bundle install --without default
script: 
  - mkdir cookbooks
  - bundle exec rake test:foodcritic
  - bundle exec rake test:knife
