language: ruby
notifications:
  email: false
rvm:
  - 1.9.3 # Same as Ariadne host env
install: bundle install --without default
script: 
  - bundle exec foodcritic cookbooks-*/* -I test/support/foodcritic/* -t '~CINK001' -t '~FC011' -t '~FC031' --epic-fail ''
  - mkdir cookbooks
  - bundle exec knife cookbook test $(ls -m cookbooks-override | tr -d ',') $(ls -m cookbooks-projects | tr -d ',') --config=test/support/knife.rb
