language: ruby
rvm:
  - 1.9.3 # Same as Ariadne host env
install: bundle install --without default
script: |
  bundle exec foodcritic cookbooks-override/* \
    --include test/support/foodcritic/* \
    --epic-fail='' \
    --tags ~CINK001 \
    --tags ~FC011 \
    --tags ~FC031
